### ISSUE TITLE
app wordt afgesloten.

### ISSUE THREAD

**Issue by nickyzoontjens** [nlrb/com.intesis.acwm#1]
Hallo,

Ik heb de app er door een maat op laten zetten, omdat ik net iets te weinig kennis heb. maar hij zegt dat aangegeven wordt dat er een foutje in de code zit. De app staat wel op homey nu, maar wordt telkens afgesloten. heb jij enig idee watdit kan zijn, of kan je misschien in mij homey kijken wat er fout gaat?

**Comment by nlrb** [comment]
Assume to be same issue as #2.
