### ISSUE TITLE
Crash op Homey

### ISSUE THREAD

**Issue by willempie68** [nlrb/com.intesis.acwm#2]
Hallo Ramon,

Ik heb jouw app geinstalleerd op mijn Homey via ICL.

De app is zichtbaar in het lijstjes met apps (Intesis Airconwithme)

Krijg hem alleen niet aan de praat.

Als ik hem opstart krijg ik in een rode balk bovenin dat de app crasht during loading en de melding dat de app is gestopt met werken. 

Weet jij wellicht wat ik fout doe ?

Ik ben bereid een donatie te doen voor jouw oplossing/antwoord.

**Comment by nlrb** [comment]
Hi, heb je een crash log? Wat zie je als je de app start met `-run`?

**Comment by willempie68** [comment]
Hallo Ramon,

Ik zie het volgende in mijn homey app
![IMG_4711](https://user-images.githubusercontent.com/67743580/87922144-d7e33000-ca7b-11ea-93cc-276e5dbc427c.PNG)
en
![IMG_4712](https://user-images.githubusercontent.com/67743580/87922180-e7627900-ca7b-11ea-8ef3-216394942e6f.PNG)

**Comment by willempie68** [comment]
hallo Ramon,

Ik heb nog even zitten lezen op het homey.athom forum.

Kan het te maken hebben met package.json files ?

Groet, Wim

**Comment by nlrb** [comment]
Hi Wim,

Ja, dat is idd het probleem. Ze hebben op een gegeven moment de CLI tools aangepast en die is nu nodig. Kan je die zelf maken?

Grtz,
-Ramón.

**Comment by willempie68** [comment]
Hoi Ramon,

hahaha, nee dat gaat mij niet lukken. Ik ben een complete leek op dat gebied.
Als jij dat zou kunnen, zou ik je zeer dankbaar en erkentelijk zijn.
Ik wil jou daar ook zeker een donatie voor geven.

Groet, Wim
